#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM combo1[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM combo2[] = {KC_F, KC_D, COMBO_END};

const uint16_t PROGMEM combo3[] = {KC_U, KC_I, COMBO_END};
const uint16_t PROGMEM combo4[] = {KC_R, KC_E, COMBO_END};

const uint16_t PROGMEM combo5[] = {KC_M, KC_COMM, COMBO_END};
const uint16_t PROGMEM combo6[] = {KC_V, KC_C, COMBO_END};

const uint16_t PROGMEM combo7[] = {KC_H, KC_J, COMBO_END};
const uint16_t PROGMEM combo8[] = {KC_G, KC_F, COMBO_END};

const uint16_t PROGMEM combo9[]  = {KC_Y, KC_U, COMBO_END};
const uint16_t PROGMEM combo10[] = {KC_T, KC_R, COMBO_END};

const uint16_t PROGMEM combo11[] = {KC_N, KC_M, COMBO_END};
const uint16_t PROGMEM combo12[] = {KC_B, KC_V, COMBO_END};

const uint16_t PROGMEM combo13[] = {KC_Q, KC_W, COMBO_END};

const uint16_t PROGMEM combo14[] = {KC_SLSH, KC_Z, COMBO_END};

combo_t key_combos[] = {
    COMBO(combo1, KC_ESC),   COMBO(combo2, KC_ESC),

    COMBO(combo3, KC_RPRN),  COMBO(combo4, KC_LPRN),

    COMBO(combo5, KC_RBRC),  COMBO(combo6, KC_LBRC),

    COMBO(combo7, CW_TOGG),  COMBO(combo8, CW_TOGG),

    COMBO(combo9, KC_RCBR),  COMBO(combo10, KC_LCBR),

    COMBO(combo11, KC_GT),   COMBO(combo12, KC_LT),

    COMBO(combo13, KC_AT),

    COMBO(combo14, QK_BOOT),

};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_LSFT), LT(1, KC_BSPC), LT(1, KC_SPC), LCTL_T(KC_ENT)),
                                                              [1] = LAYOUT_split_3x5_2(KC_GRV, KC_QUOT, KC_DQUO, KC_AMPR, KC_CIRC, KC_EXLM, KC_EQL, KC_PLUS, KC_ASTR, KC_DLR, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_HASH, KC_BSLS, KC_TILD, KC_PIPE, KC_PERC, KC_QUES, KC_EQL, KC_MINS, KC_SLSH, KC_UNDS, KC_TAB, LT(2, KC_BSPC), LT(2, KC_SPC), KC_ESC),
                                                              [2] = LAYOUT_split_3x5_2(LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), LGUI(KC_4), LGUI(KC_5), LGUI(KC_6), LGUI(KC_7), LGUI(KC_8), LGUI(KC_9), LGUI(KC_0), SGUI(KC_Q), KC_TRNS, SGUI(KC_S), SGUI(KC_ENT), SGUI(KC_H), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, LGUI(KC_P), KC_LSFT, LGUI(KC_F), LGUI(KC_T), LGUI(KC_M), KC_TRNS, LGUI(KC_H), LGUI(KC_J), LGUI(KC_K), LGUI(KC_L), LGUI(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [3] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, KC_TRNS, KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS, KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MINS, KC_BSLS, KC_GRV, KC_TRNS, RM_PREV, KC_TRNS, KC_TRNS, RM_NEXT),
                                                              [4] = LAYOUT_split_3x5_2(KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT, KC_TRNS, KC_NO, KC_EQL, KC_PLUS, KC_PERC, KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_VOLU),
                                                              [5] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS, KC_NO, LCTL(KC_LALT), KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [6] = LAYOUT_split_3x5_2(KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_1, KC_2, KC_3, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_PAST, KC_4, KC_5, KC_6, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
                                                              [7] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_COLN, KC_ESC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS, KC_PERC, KC_SLSH, KC_ENT, KC_TRNS, DF(1), KC_LGUI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_EXLM, KC_TRNS, DF(0), KC_TRNS, RALT_T(KC_COMM), RCTL_T(KC_DOT), QK_BOOT, KC_TRNS, KC_TAB, KC_NO, KC_TRNS)};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
